language: node_js
node_js:
    - "stable"
cache: yarn

install:
    - yarn global add codecov
    - yarn

before-script:
    - echo "Running scripts"
script:
    - yarn format
    - yarn test
    - codecov

after-success:
    - echo "Success"
after-failure:
    - echo "Failure"
