language: node_js
node_js:
    - "stable"
cache: yarn

install:
    - yarn

before-script:
    - echo "Running scripts"
script:
    - yarn format
    - yarn test

after-success:
    - echo "Success"
after-failure:
    - echo "Failure"
